# Generated by Django 5.2.7 on 2026-01-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.TextField()),
                ('input_preview', models.CharField(max_length=255)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='SAFE', max_length=16)),
                ('recommended_disclosure', models.CharField(choices=[('PUBLIC_SAFE', 'Public Safe'), ('INTERNAL_ONLY', 'Internal Only'), ('RESTRICTED', 'Restricted')], default='INTERNAL_ONLY', max_length=32)),
                ('flag_reasons', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('safe_version', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
